### ISSUE TITLE
Header meta menu weird when squeezed

### ISSUE THREAD

**Issue by davidknezic** [axa-group/web-toolkit#32] opened 2016-11-01 12:37 UTC
![img_1999](https://cloud.githubusercontent.com/assets/198988/19889979/5a126770-a038-11e6-8ddf-45d155be7c9a.PNG)

**Comment by FKSI** [comment] 2017-01-25 08:24
By design the meta-header shouldn't exist on small breakpoints, the content is move inside the burger menu. Closing.

**Closed as completed by FKSI** 2017-01-25 08:24 UTC
Labels: bug
